[package]
name = "civs"
version = "0.1.1"
authors = ["merl <merl.001.mia@gmail.com>"]
edition = "2018"

[features]
debug = []

[dev-dependencies]
rand = "0.7"

[dependencies]
bincode = "1.0"
byteorder = "1.3"
serde = { version = "1.0", features = ["derive"] }
